[general]
live_config_reload = true

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
size = 12.3

[window]
padding = { x = 0, y = 0 }
opacity = 0.7
decorations = "none"

[mouse]
hide_when_typing = true
