[general]
live_config_reload = true
import = [
    "./catppuccin-macchiato.toml"
]

[env]
term = "xterm-256color"

[font]
normal = { family = "JetBrainsMono Nerd Font" }
bold = { family = "JetBrainsMono Nerd Font" }
italic = { family = "JetBrainsMono Nerd Font" }
bold_italic = { family = "JetBrainsMono Nerd Font" }
size = 12.6

[window]
padding = { x = 0, y = 6 }
opacity = 1
blur = false
decorations = "buttonless"
startup_mode = "Maximized"

[mouse]
hide_when_typing = true

