[general]
live_config_reload = true
import = [
    "./catppuccin-macchiato.toml"
]

[font]
normal = { family = "JetBrainsMono Nerd Font" }
bold = { family = "JetBrainsMono Nerd Font" }
italic = { family = "JetBrainsMono Nerd Font" }
bold_italic = { family = "JetBrainsMono Nerd Font" }
size = 13.1

[window]
padding = { x = 0, y = 0 }
opacity = 0.7
blur = true
decorations = "none"
startup_mode = "Maximized"

[mouse]
hide_when_typing = true

